// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/api.dart';
import 'api/game.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Cell dco_decode_box_autoadd_cell(dynamic raw);

  @protected
  GameTurn dco_decode_box_autoadd_game_turn(dynamic raw);

  @protected
  Player dco_decode_box_autoadd_player(dynamic raw);

  @protected
  Cell dco_decode_cell(dynamic raw);

  @protected
  GameTurn dco_decode_game_turn(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<Cell> dco_decode_list_cell(dynamic raw);

  @protected
  List<List<Cell>> dco_decode_list_list_cell(dynamic raw);

  @protected
  Player? dco_decode_opt_box_autoadd_player(dynamic raw);

  @protected
  Player dco_decode_player(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Cell sse_decode_box_autoadd_cell(SseDeserializer deserializer);

  @protected
  GameTurn sse_decode_box_autoadd_game_turn(SseDeserializer deserializer);

  @protected
  Player sse_decode_box_autoadd_player(SseDeserializer deserializer);

  @protected
  Cell sse_decode_cell(SseDeserializer deserializer);

  @protected
  GameTurn sse_decode_game_turn(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<Cell> sse_decode_list_cell(SseDeserializer deserializer);

  @protected
  List<List<Cell>> sse_decode_list_list_cell(SseDeserializer deserializer);

  @protected
  Player? sse_decode_opt_box_autoadd_player(SseDeserializer deserializer);

  @protected
  Player sse_decode_player(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cell(Cell self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_game_turn(
    GameTurn self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_player(Player self, SseSerializer serializer);

  @protected
  void sse_encode_cell(Cell self, SseSerializer serializer);

  @protected
  void sse_encode_game_turn(GameTurn self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell(List<Cell> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_cell(
    List<List<Cell>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_player(
    Player? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player(Player self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
