// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'game.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Cell switchFn({required Cell cell}) =>
    RustLib.instance.api.crateApiApiSwitchFn(cell: cell);

Cell makeMove({required Cell cell, required Player turn}) =>
    RustLib.instance.api.crateApiApiMakeMove(cell: cell, turn: turn);

Player switchTurn({required Player turn}) =>
    RustLib.instance.api.crateApiApiSwitchTurn(turn: turn);

GameTurn newGame() => RustLib.instance.api.crateApiApiNewGame();

bool checkIfFull({required GameTurn gameTurn}) =>
    RustLib.instance.api.crateApiApiCheckIfFull(gameTurn: gameTurn);

Player? checkWinner({required GameTurn gameTurn}) =>
    RustLib.instance.api.crateApiApiCheckWinner(gameTurn: gameTurn);
